---
Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
      #   BucketName: 
      #   CorsConfiguration: 
      #   LifecycleConfiguration: 
      #   NotificationConfiguration: 
      #   VersioningConfiguration: 
      #   WebsiteConfiguration: 
      #   Tags:
      #     - Key: key
      #       Value: value"