---
Parameters:
  S3BucketName:
    Type: String
    Description: "Enter Bucket Name"
  S3AccessControl:
    Type: String
    Default: Private
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead

Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: !Ref S3AccessControl
        BucketName: !Ref S3BucketName
      #   CorsConfiguration: 
      #   LifecycleConfiguration: 
      #   NotificationConfiguration: 
      #   VersioningConfiguration: 
      #   WebsiteConfiguration: 
      #   Tags:
      #     - Key: key
      #       Value: value"