---
Parameters:
  EnvironmentName:
    Description: Environemnt name
    Type: String
    AllowedValues: [dev, prod]
    ConstraintDescription: Environment must be dev or prod

Mappings:
  EC2InstanceAMI:
    us-west-1:
      HVM64: ami-03130878b60947df3
    eu-central-1:
      HVM64: ami-03c3a7e4263fd998c
  
  EC2InstanceType:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.micro

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ EC2InstanceAMI, !Ref 'AWS::Region', HVM64 ]
      InstanceType: !FindInMap [ EC2InstanceType, !Ref EnvironmentName, instanceType ] 
      