--- 
Parameters:
  LatestAmiID:
    Type: String
    Default: ami-03c3a7e4263fd998c

  InstanceType:
    Type: String 
    Default: t2.micro

  SecGroup:
    Type: String
    Default: Frankfurt_EC2

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      
      #AvailabilityZone: String
     
      ImageId: !Ref LatestAmiID
      
      InstanceType: !Ref InstanceType
      
      SecurityGroups:
        - !Ref SecGroup
     
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum install -y httpd
          sudo chown -R -v ec2-user /var/www/html/
          echo "Hello World $(hostname -f) version 4.0" > /var/www/html/index.html
          systemctl httpd start
         

  